package frc.robot.Utils;

public class LEDColors {
    public enum Colors {
        RAINBOW_PALETTE(-0.99),
        RAINBOW_PARTY(-0.97),
        RAINBOW_OCEAN(-0.95),
        RAINBOW_LAVA(-0.93),
        RAINBOW_FOREST(-0.91),
        RAINBOW_GLITTER(-.89),
        CONFETTI(-.87),
        RED_SHOT(-.85),
        BLUE_SHOT(-.83),
        WHITE_SHOT(-.81),
        SINELON_RAINBOW(-.79),
        SINELON_PARTY(-.77),
        SINELON_OCEAN(-.75),
        SINELON_LAVA(-.73),
        SINELON_FOREST(-.71),
        BPM_RAINBOW(-.69),
        BPM_PARTY(-.67),
        BPM_OCEAN(-.65),
        BPM_LAVA(-.63),
        BPM_FOREST(-.61),
        FIRE_MED(-.59),
        FIRE_LARGE(-.57),
        TWINKLES_RAINBOW(-.55),
        TWINKLES_PARTY(-.53),
        TWINKLES_OCEAN(-.51),
        TWINKLES_LAVA(-.49),
        TWINKLES_FOREST(-.47),
        CWAVES_RAINBOW(-.45),
        CWAVES_PARTY(-.43),
        CWAVES_OCEAN(-.41),
        CWAVES_LAVA(-.39),
        CWAVES_FOREST(-.37),
        LSCANNER_RED(-.35),
        LSCANNER_GRAY(-.33),
        LCHASE_RED(-.31),
        LCHASE_BLUE(-.29),
        LCHASE_GRAY(-.27),
        HEARTBEAT_RED(-.25),
        HEARTBEAT_BLUE(-.23),
        HEARTBEAT_WHITE(-.21),
        HEARTBEAT_GRAY(-.19),
        BREATH_RED(-.17),
        BREATH_BLUE(-.15),
        BREATH_GRAY(-.13),
        STROBE_RED(-.11),
        STROBE_BLUE(-.9),
        STROBE_GOLD(-.7),
        STROBE_WHITE(-.5),
        BLEND2_BLACK1(-.3),
        LSCANNER1(-.1),
        LCHASE1(0.1),
        HEARTBEAT_SLOW1(0.3),
        HEARTBEAT_MEDIUM1(0.5),
        HEARTBEAT_FAST1(0.7),
        BREATH_SLOW1(0.9),
        BREATH_FAST1(0.11),
        SHOT1(0.13),
        STROBE1(0.15),
        BLEND2_BLACK2(0.17),
        LSCANNER2(0.19),
        LCHASE2(0.21),
        HEARTBEAT_SLOW2(0.23),
        HEARTBEAT_MEDIUM2(0.25),
        HEARTBEAT_FAST2(0.27),
        BREATH_SLOW2(0.29),
        BREATH_FAST2(0.31),
        SHOT2(0.33),
        STROBE2(0.35),
        SPARKLE_1_2(0.37),
        SPARKLE_2_1(0.39),
        COLOR_GRAD_1_2(0.41),
        BPM_COLOR_1_2(0.43),
        END_2END_BLEND_COLOR_1_2(0.45),
        END_2END_BLEND(0.47),
        COLOR_1_2_NOBLEND(0.49),
        TWINKLES_COLOR_1_2(0.51),
        CWAVES_COLOR_1_2(.53),
        SINELON_COLOR_1_2(0.55),
        HOT_PINK(0.57),
        DARK_RED(0.59),
        RED(0.61),
        RED_ORANGE(0.63),
        ORANGE(0.65),
        GOLD(0.67),
        YELLOW(0.69),
        LAWN_GREEN(0.71),
        LIME(0.73),
        DARK_GREEN(0.75),
        GREEN(0.77),
        BLUE_GREEN(0.79),
        AQUA(0.81),
        SKY_BLUE(0.83),
        DARK_BLUE(0.85),
        BLUE(0.87),
        BLUE_VIOLET(0.89),
        VIOLET(0.91),
        WHITE(0.93),
        GRAY(0.95),
        DARK_GRAY(0.97),
        BLACK(0.99);



        

        public final double sparkValue;

        private Colors(double value) {
            sparkValue = value;
        }
    }
       
}
